// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function AddHistory(arg1:string):Promise<void>;

export function ClearHistory():Promise<void>;

export function DeleteHistory(arg1:string):Promise<void>;

export function FetchRepo(arg1:string):Promise<types.RepoBundle>;

export function ForceRefresh(arg1:string):Promise<types.RepoBundle>;

export function LoadHistory():Promise<Array<string>>;

export function SetToken(arg1:string):Promise<void>;
