// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHistory(arg1) {
  return window['go']['main']['App']['AddHistory'](arg1);
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function DeleteHistory(arg1) {
  return window['go']['main']['App']['DeleteHistory'](arg1);
}

export function FetchRepo(arg1) {
  return window['go']['main']['App']['FetchRepo'](arg1);
}

export function ForceRefresh(arg1) {
  return window['go']['main']['App']['ForceRefresh'](arg1);
}

export function LoadHistory() {
  return window['go']['main']['App']['LoadHistory']();
}

export function SetToken(arg1) {
  return window['go']['main']['App']['SetToken'](arg1);
}
